#将一些常量抽取到yml文件中
server:
  port: 8086

leyou:
  sms:
    accessKeyId: LTAI5tE9KLFfzArRyjZyGCnG     # 你自己的accessKeyId
    accessKeySecret: WswWYEqsL92RrXa8RpnFml7cnGnk3s    # 你自己的AccessKeySecret
    signName: 程耀醇的个人网站                 # 签名名称
    verifyCodeTemplate: SMS_270370268 # 模板名称

spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.75.128
